# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "transmission-exporter-unstable-${version}";
  version = "2020-02-29";
  rev = "6ea4be9cbe99a9557b6bb71c1afdcef15ccd5551";

  goPackagePath = "github.com/arachnist/transmission-exporter";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/arachnist/transmission-exporter.git";
    sha256 = "0nfhz6z75pm44vifk1w3zb85pv4vpypvjc1509b4zg9g9pk39zyg";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
